# install aws cli to interact with AWS to push image to ECR
---
- name: Install unzip package on Ubuntu
  apt:
    name: unzip
    state: present

- name: Download AWS CLI v2
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
  args:
    creates: /tmp/awscliv2.zip

- name: Unzip AWS CLI
  shell: |
    unzip /tmp/awscliv2.zip -d /tmp
  args:
    creates: /tmp/aws

- name: Install AWS CLI
  shell: |
    /tmp/aws/install
  args:
    creates: /usr/local/bin/aws

- name: Remove temporary files
  file:
    path: /tmp/awscliv2.zip
    state: absent
# Check kubectl version
- name: Check kubectl version
  shell: aws --version
  register: aws_version
# print aws version
- name: print aws version
  debug:
    var: aws_version.stdout