---
- name: install AWS CLI
  hosts: EC2
  roles:
    - jenkins

- name: install AWS CLI
  hosts: EC2
  roles:
    - aws_cli

- name: install kubectl
  hosts: EC2
  roles:
    - kubectl

- name: install Docker
  hosts: EC2
  roles:
    - docker
