name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  checkout-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Upgrade pip moudule version and Install Requriements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: build docker image and push it to dockerhub
      run: |
        docker build -t todo-python-app .
        docker tag todo-python-app ${{ secrets.DOCKERHUB_USERNAME }}/todo-python-app:${{ github.sha }}
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_TOKEN}}
        docker push mahmoudhassan9/todo-python-app:${{ github.sha }}
